# KMeans
[Lecture 1](https://courses.edx.org/courses/course-v1:Microsoft+DAT210x+4T2017/courseware/bd8efb20-877f-92c5-775b-80115150d0bf/ee5ead40-6bed-c482-d738-1a2dd2c1526f/?activate_block_id=block-v1%3AMicrosoft%2BDAT210x%2B4T2017%2Btype%40sequential%2Bblock%40ee5ead40-6bed-c482-d738-1a2dd2c1526f)
[Lecture 2](https://courses.edx.org/courses/course-v1:Microsoft+DAT210x+4T2017/courseware/bd8efb20-877f-92c5-775b-80115150d0bf/ee5ead40-6bed-c482-d738-1a2dd2c1526f/?activate_block_id=block-v1%3AMicrosoft%2BDAT210x%2B4T2017%2Btype%40sequential%2Bblock%40ee5ead40-6bed-c482-d738-1a2dd2c1526f)
[Lecture 3](https://courses.edx.org/courses/course-v1:Microsoft+DAT210x+4T2017/courseware/bd8efb20-877f-92c5-775b-80115150d0bf/ee5ead40-6bed-c482-d738-1a2dd2c1526f/?activate_block_id=block-v1%3AMicrosoft%2BDAT210x%2B4T2017%2Btype%40sequential%2Bblock%40ee5ead40-6bed-c482-d738-1a2dd2c1526f)

Quick demo:

In [22]:
import pandas as pd

df = pd.read_csv('./Datasets/breast-cancer-wisconsin.data', header=None)

In [9]:
from sklearn.cluster import KMeans

In [10]:
kmeans = KMeans(n_clusters=5)

In [19]:
df.iloc[:, 6] = pd.to_numeric(df.iloc[:, 6], errors='coerce')
df = df.dropna()

In [20]:
kmeans.fit(df)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=5, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [22]:
labels = kmeans.predict(df)
labels

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4,
       4, 4, 4, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [23]:
centroids = kmeans.cluster_centers_
centroids

array([[  7.60220279e+05,   4.22522523e+00,   3.14414414e+00,
          3.08108108e+00,   3.19819820e+00,   3.29729730e+00,
          3.83783784e+00,   3.45045045e+00,   2.85585586e+00,
          1.66666667e+00,   2.75675676e+00],
       [  1.34543520e+07,   1.00000000e+00,   1.00000000e+00,
          3.00000000e+00,   1.00000000e+00,   2.00000000e+00,
          1.00000000e+00,   2.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   2.00000000e+00],
       [  1.20316339e+06,   4.44710579e+00,   3.13373253e+00,
          3.15968064e+00,   2.69061876e+00,   3.21157685e+00,
          3.33333333e+00,   3.38323353e+00,   2.81437126e+00,
          1.56886228e+00,   2.65868263e+00],
       [  8.23370400e+06,   4.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   2.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   2.00000000e+00],
       [  3.84674638e+05,   4.81159420e+00,   3.34782609e+00,
          3.86

# Supervised Learning
[Lecture](https://courses.edx.org/courses/course-v1:Microsoft+DAT210x+4T2017/courseware/bd8efb20-877f-92c5-775b-80115150d0bf/5412d1ea-a9d5-47b6-8350-181f2dd091d1/?child=first)

Sample from further discussion:

## SciKit-Learn

In [16]:
from sklearn.model_selection import train_test_split
data   = [0,1,2,3,4,5,6,7,8,9]  # input dataframe samples
labels = [0,0,0,0,0,1,1,1,1,1]  # the function we're training is " >4 "

data_train, data_test, label_train, label_test = train_test_split(data, labels, test_size=0.5, random_state=7)

In [17]:
data_train

[9, 7, 3, 6, 4]

In [18]:
label_train

[1, 1, 0, 1, 0]

In [19]:
data_test

[8, 5, 0, 2, 1]

In [20]:
label_test

[1, 1, 0, 0, 0]

# Example from lecture
(Note: This model relies on more dimensions in the data - need to find a model that can predict based on 1D data)
```python
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)
clf.fit(data_train, label_train)
```
Create predictions:
```python
from sklearn.metrics import accuracy_score

# Returns an array of predictions:
predictions = my_model.predict(data_test) 
```
Score model:
```python
# The actual answers:
label_test

accuracy_score(label_test, predictions)

accuracy_score(label_test, predictions, normalize=False)
```

In [34]:
# From now on, you only train on a "portion" of your dset:
X_train = pd.DataFrame([ [data_train[0]],[data_train[1]], [data_train[2]], [data_train[3]], [data_train[4]] ])
y_train = pd.DataFrame([ [label_train[0]],[label_train[1]],[label_train[2]],[label_train[3]],[label_train[4]] ])

In [35]:
X_train

0
0  9
1  7
2  3
3  6
4  4

In [51]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train) 

# You can pass in a dframe or an ndarray
label_predict = model.predict([[data_test[0]],[data_test[1]], [data_test[2]], [data_test[3]], [data_test[4]]])
label_predict

/Users/malcolmgin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


array([1, 0, 0, 0, 0])

In [50]:
# Bogus comparison:
# Never do this in reality - but to illustrate the scoring.
accuracy_score(label_predict, label_train)

0.59999999999999998

# K-Nearest Neighbors Classification
[Discussion](https://courses.edx.org/courses/course-v1:Microsoft+DAT210x+4T2017/courseware/bd8efb20-877f-92c5-775b-80115150d0bf/1c89a87b-3f21-cc7c-2cf1-c289a564b7ea/?child=first)
[Lecture - How does K-Neighbors Work?](https://courses.edx.org/courses/course-v1:Microsoft+DAT210x+4T2017/courseware/bd8efb20-877f-92c5-775b-80115150d0bf/1c89a87b-3f21-cc7c-2cf1-c289a564b7ea/?child=first)
[Lecture - SciKit-Learn and K-Neighbors](https://courses.edx.org/courses/course-v1:Microsoft+DAT210x+4T2017/courseware/bd8efb20-877f-92c5-775b-80115150d0bf/1c89a87b-3f21-cc7c-2cf1-c289a564b7ea/?child=first)

Note distance weighting can be skewed by non-uniform cluster sizes, so be careful.